// Generated by https://quicktype.io

import { TGender, TValidSize } from './ProductInterface'

export interface IOrderOne {
  id: string
  user: UserOrderOne
  numberOfItem: number
  subtotal: number
  tax: number
  total: number
  isPaid: boolean
  paidAt: null
  paymetResult: null
  orderItems: OrderItemOrderOne[]
  inCart: boolean
  address: AddressOrderOne
}

export interface AddressOrderOne {
  id: string
  address: string
  address0: string
  postalCode: string
  city: string
  phono: string
  country: CountryOrderOne
  user: UserOrderOne
  createdAt: string
  updatedAt: string
}

export interface CountryOrderOne {
  id: string
  label: string
  value: string
}

export interface UserOrderOne {
  id: string
  name: string
  email: string
  role: string
  createdAt: string
  updatedAt: string
}

export interface OrderItemOrderOne {
  id: string
  image: string
  price: number
  slug: string
  title: string
  gender: TGender
  size: TValidSize
  quantity: number
}
