// Generated by https://quicktype.io

import { TGender, TValidSize } from './ProductInterface'

export interface IOrder {
  numberOfItem: number
  subtotal: number
  tax: number
  total: number
  orderItems: OrderItem[]
}

export interface OrderItem {
  id: string
  image: string
  price: number
  slug: string
  title: string
  gender: TGender
  size: TValidSize
  quantity: number
}
